import { describe, expect, it, vi } from "vitest";

// next/font/google's real module is generated by Next's build-time compiler
// (the installed package file is empty outside a Next.js build): mocked here
// with fake loaders that record their call options. The module under test
// calls all 4 loaders once, at module scope (docs/04-nextjs.md), so every
// assertion below shares a single import: mocks are cleared between tests
// (vitest 5 default), and re-importing wouldn't call the loaders again
// (module cache).
const loader = vi.fn((options: unknown) => ({ variable: "--font-theme", className: "font-mock", options }));

vi.mock("next/font/google", () => ({
  Fraunces: (options: unknown) => loader({ font: "Fraunces", ...(options as object) }),
  Space_Grotesk: (options: unknown) => loader({ font: "Space_Grotesk", ...(options as object) }),
  Inter: (options: unknown) => loader({ font: "Inter", ...(options as object) }),
  Nunito: (options: unknown) => loader({ font: "Nunito", ...(options as object) }),
}));

describe("lib/fonts", () => {
  it("declares the 4 keys, resolves each to its font, falls back on unknown, and calls every loader once", async () => {
    const { FONT_KEYS, fontFor } = await import("./fonts");

    expect(FONT_KEYS).toEqual(["serif", "grotesk", "sans", "rounded"]);
    expect(fontFor("serif").variable).toBe("--font-theme");
    expect(fontFor("unknown-font")).toEqual(fontFor("sans"));

    const fonts = loader.mock.calls.map(([options]) => (options as { font: string }).font);
    expect(fonts.sort()).toEqual(["Fraunces", "Inter", "Nunito", "Space_Grotesk"]);
    for (const [options] of loader.mock.calls) {
      expect(options).toMatchObject({ variable: "--font-theme", display: "swap", preload: false });
    }
  });
});
